### ISSUE TITLE
QR code validation for security reasons

### ISSUE THREAD

**Issue by MareNectaris** [DSmakerteam/DDarmist#14]
![image](https://user-images.githubusercontent.com/30724686/71897451-fd70b200-3199-11ea-87eb-8ef1cd283acc.png)

**Comment by MareNectaris** [comment]
When QR code (long enough to crash the app) is read:

> 2020-01-07 22:10:45.899 24774-24774/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: site.isnt.ddarmist, PID: 24774
>     java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49374, result=-1, data=Intent { act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to activity {site.isnt.ddarmist/site.isnt.ddarmist.views.activitys.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=64; index=-1
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7050)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
>      Caused by: java.lang.StringIndexOutOfBoundsException: length=64; index=-1
>         at java.lang.String.charAt(Native Method)
>         at site.isnt.ddarmist.libs.functions.Util$Companion.victekb64tob64(Util.kt:36)
>         at site.isnt.ddarmist.libs.functions.Util$Companion.victekb64decode(Util.kt:42)
>         at site.isnt.ddarmist.views.activitys.MainActivity.onActivityResult(MainActivity.kt:167)
>         at android.app.Activity.dispatchActivityResult(Activity.java:7759)
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652) 
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.app.ActivityThread.main(ActivityThread.java:7050) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
